--- #YAML:1.0
name:                Color-Calc
version:             1.05
abstract:            Simple calculations with RGB colors.
license:             perl
author:              
    - Claus Faerber <CFAERBER@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Graphics::ColorNames:          0.32
    Graphics::ColorNames::WWW:     0.01
    Params::Validate:              0.75
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
