---
name: Color-Calc
version: 1.060
author:
  - 'Claus Färber <CFAERBER@cpan.org>'
abstract: Simple calculations with RGB colors.
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
  Test::NoWarnings: 0
requires:
  Graphics::ColorNames: 2.1
  Graphics::ColorNames::HTML: 0
  Graphics::ColorNames::WWW: 0.01
  Params::Validate: 0.75
configure_requires:
  Module::Build: 0.35
provides:
  Color::Calc:
    file: lib/Color/Calc.pm
    version: 1.060
  Color::Calc::WWW:
    file: lib/Color/Calc/WWW.pm
    version: 1.060
no_index:
  directory: eg
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
