---
abstract: 'Simple calculations with RGB colors.'
author:
  - 'Claus Färber <CFAERBER@cpan.org>'
build_requires:
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Color-Calc
no_index:
  directory: eg
provides:
  Color::Calc:
    file: lib/Color/Calc.pm
    version: 1.061
  Color::Calc::WWW:
    file: lib/Color/Calc/WWW.pm
    version: 1.060
requires:
  Graphics::ColorNames: 2.1
  Graphics::ColorNames::HTML: 0
  Graphics::ColorNames::WWW: 0.01
  Params::Validate: 0.75
resources:
  license: http://dev.perl.org/licenses/
version: 1.061
